// Registration action types
export const NEXT_STEP = "NEXT_STEP";
export const PREVIOUS_STEP = "PREVIOUS_STEP";

// Authentication action types
export const LOGIN = "LOGIN";
export const UPDATE_PHONE_NUMBER = "UPDATE_PHONE_NUMBER";
export const UPDATE_DEACTIVATED_USER = "UPDATE_DEACTIVATED_USER";

// User actions types
export const FETCH_USER_DATA_SUCCESS = "FETCH_USER_DATA_SUCCESS";
export const FETCH_USER_DATA_FAILURE = "FETCH_USER_DATA_FAILURE";
export const DEACTIVATE_USER_REQUEST = "DEACTIVATE_USER_REQUEST";
export const DEACTIVATE_USER_SUCCESS = "DEACTIVATE_USER_SUCCESS";
export const DEACTIVATE_USER_FAILURE = "DEACTIVATE_USER_FAILURE";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const UPDATE_CURRENT_USER = "UPDATE_CURRENT_USER";
export const LOGOUT = "LOGOUT";

// Linkup actions types
export const FETCH_LINKUPS_SUCCESS = "FETCH_LINKUPS_SUCCESS";
export const SET_IS_LOADING = "SET_IS_LOADING";
export const UPDATE_LINKUP_SUCCESS = "UPDATE_LINKUP_SUCCESS";
export const UPDATE_LINKUP_LIST = "UPDATE_LINKUP_LIST";
export const MARK_LINKUPS_AS_EXPIRED_SUCCESS =
  "MARK_LINKUPS_AS_EXPIRED_SUCCESS";

// Editing linkup actions types
export const SET_EDITING_LINKUP = "SET_EDITING_LINKUP";
export const CLEAR_EDITING_LINKUP = "CLEAR_EDITING_LINKUP";

// Messages action types
export const SET_MESSAGES_DATA = "SET_MESSAGES_DATA";

// Notifications action types
export const FETCH_UNREAD_NOTIFICATIONS_COUNT =
  "FETCH_UNREAD_NOTIFICATIONS_COUNT";
export const UPDATE_UNREAD_NOTIFICATIONS_COUNT =
  "UPDATE_UNREAD_NOTIFICATIONS_COUNT";

// User Sent Requests types
export const ADD_SENT_REQUEST = "ADD_SENT_REQUEST";
